services:
  backend:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    command: "./.venv/bin/uvicorn main:app --host ${SERVER_HOST} --port ${SERVER_PORT} --reload"
    volumes:
      - ./backup/service/eval/job_data:/app/job_data
      - ./backup/service/eval/eval_job_data:/app/eval_job_data
      - ./backup/downloads:/app/downloads
      - ./backup/constants:/app/constants
  vast-proxy:
    build:
      context: .
      dockerfile: remote_vast_server/Dockerfile
    env_file:
      - .env
    ports:
      - "${REMOTE_VAST_PORT:-9000}:${REMOTE_VAST_PORT:-9000}"
    volumes:
      - ./backup/service/eval/job_data:/app/job_data
      - ./backup/service/eval/eval_job_data:/app/eval_job_data
      - ./backup/downloads:/app/downloads
      - ./backup/constants:/app/constants
