services:
  postgres:
    env_file:
      - .env
    image: postgres:15.4
    container_name: prg_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped

  qdrant:
    env_file:
      - .env
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: qdrant
    ports:
      - "${QDRANT_HTTP_PORT}:${QDRANT_HTTP_PORT}"
      - "${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}"
    expose:
      - "${QDRANT_HTTP_PORT}"
      - "${QDRANT_GRPC_PORT}"
      - "6335"
    configs:
      - source: qdrant_config
        target: ${QDRANT_CONFIG_PATH}
    volumes:
      - qdrant_data:/qdrant/storage   # ✅ 안전한 Docker volume 사용

  backend:
    build: .
    container_name: plateerag_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    volumes:
      - .:/app:delegated
      - ./backup/service/eval/job_data:/app/job_data
      - ./backup/service/eval/eval_job_data:/app/eval_job_data
      - ./backup/downloads:/app/downloads
      - ./backup/constants:/app/constants
    depends_on:
      - postgres
      - qdrant
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data:
configs:
  qdrant_config:
    content: |
      log_level: INFO