name: Build & Deploy Backend (GitOps)

on:
  push:
    branches: [feature/k3s-1]

env:
  # ---- Image & Infra ----
  IMAGE_NAME: xgen-backend/api
  BASE_PATH: apps/backend/base

  # ---- Build args for the new Dockerfile ----
  # Choose only the groups you truly need in prod.
  # e.g. "rag,jp-core" if you use embeddings + JP tokenization, or "" for minimal.
  UV_GROUPS: ""
  # 0 = skip torch; 1 = install CPU-only torch wheels (smaller than CUDA)
  INSTALL_TORCH: "0"
  TORCH_VER: "2.7.1"
  TORCHAUDIO_VER: "2.7.1"

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout backend source
        uses: actions/checkout@v4

      - name: Docker login (Nexus)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEXUS_REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Set image tag
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "TAG=sha-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build & push with the Dockerfile's build args
      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
            ${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # Disable extra attestations that older Nexus/proxies sometimes mishandle
          provenance: false
          sbom: false
          outputs: type=registry
          # Build args to wire into Dockerfile
          build-args: |
            UV_GROUPS=${{ env.UV_GROUPS }}
            INSTALL_TORCH=${{ env.INSTALL_TORCH }}
            TORCH_VER=${{ env.TORCH_VER }}
            TORCHAUDIO_VER=${{ env.TORCHAUDIO_VER }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PIPELINE_REPO }} # e.g. X2bee/k3s-pipeline
          token: ${{ secrets.PIPELINE_REPO_PAT }} # PAT with repo scope
          path: infra

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tag in kustomize
        working-directory: infra/${{ env.BASE_PATH }}
        run: |
          kustomize edit set image ${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}=${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
          echo "Updated kustomization.yaml:"
          cat kustomization.yaml

      - name: Commit & push to infra repo
        working-directory: infra
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "backend: update image to ${{ steps.vars.outputs.TAG }}"
            git push origin main
          fi
