name: Build & Deploy Backend (GitOps)

on:
  push:
    branches: [feature/k3s-1]

env:
  IMAGE_NAME: xgen-backend/api # image path in your Nexus registry
  BASE_PATH: apps/backend/base # path in k3s-pipeline where kustomization.yaml lives

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # 1) App source
      - name: Checkout backend source
        uses: actions/checkout@v4

      # 2) Login to Nexus registry
      - name: Docker login (Nexus)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEXUS_REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      # 3) Tag (short SHA)
      - name: Set image tag
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "TAG=sha-${SHORT_SHA}" >> $GITHUB_OUTPUT

      # 4) Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5) Build & push image to Nexus
      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
            ${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # keep these off for maximum compatibility with Nexus
          provenance: false
          sbom: false
          outputs: type=registry
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 6) Infra repo (kustomize)
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PIPELINE_REPO }} # e.g. X2bee/k3s-pipeline
          token: ${{ secrets.PIPELINE_REPO_PAT }} # PAT with repo or contents:write
          path: infra

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tag in kustomize
        working-directory: infra/${{ env.BASE_PATH }}
        run: |
          kustomize edit set image \
            ${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}=${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
          echo "== kustomization.yaml =="
          cat kustomization.yaml

      - name: Commit & push to infra repo
        working-directory: infra
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "backend: update image to ${{ steps.vars.outputs.TAG }}"
            git push origin main
          fi
