name: Build & Deploy Backend (GitOps)

on:
  push:
    branches: [feature/k3s-1]

env:
  IMAGE_NAME: xgen-backend/api
  BASE_PATH: apps/backend/base

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Docker login (Nexus)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEXUS_REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Set image tag
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "TAG=sha-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
            ${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          provenance: false
          sbom: false
          outputs: type=registry
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PIPELINE_REPO }}
          token: ${{ secrets.PIPELINE_REPO_PAT }}
          path: infra

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tag
        working-directory: infra/${{ env.BASE_PATH }}
        run: |
          kustomize edit set image ${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}=${{ secrets.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
          cat kustomization.yaml

      - name: Commit & push
        working-directory: infra
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "backend: update image to ${{ steps.vars.outputs.TAG }}"
          git push origin main
